// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9mDNWg9yDLnNeWDYjIxq29AI9ffc6kZI',
    appId: '1:96408666221:web:9c7498a2e5a776d180ff64',
    messagingSenderId: '96408666221',
    projectId: 'headstartflutter',
    authDomain: 'headstartflutter.firebaseapp.com',
    storageBucket: 'headstartflutter.appspot.com',
    measurementId: 'G-61RXSXTXMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx26CDo8R_I4-T3vGK6EN4lF6Fngp5rOU',
    appId: '1:96408666221:android:a01c91e1f5a8d3af80ff64',
    messagingSenderId: '96408666221',
    projectId: 'headstartflutter',
    storageBucket: 'headstartflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeJ4s9mCVcHDMKbTxJq-WlHgNTxool88E',
    appId: '1:96408666221:ios:bbb56aa003b58b5a80ff64',
    messagingSenderId: '96408666221',
    projectId: 'headstartflutter',
    storageBucket: 'headstartflutter.appspot.com',
    iosClientId: '96408666221-j90uoplhcbsj12d0pkns0nhdt0idfs0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.headstartFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeJ4s9mCVcHDMKbTxJq-WlHgNTxool88E',
    appId: '1:96408666221:ios:bbb56aa003b58b5a80ff64',
    messagingSenderId: '96408666221',
    projectId: 'headstartflutter',
    storageBucket: 'headstartflutter.appspot.com',
    iosClientId: '96408666221-j90uoplhcbsj12d0pkns0nhdt0idfs0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.headstartFlutter',
  );
}
